# Site settings
title:              Weilin Ma's Portfolio Site
email:              weilinma2018@u.northwestern.edu
description:        "Portfolio site for Weilin Ma in the MSR program at Northwestern University"
url:                "http://localhost:4000"
baseurl:            /WM_portfolio
theme:              jekyll-theme-slate

# File structure settings
image_path:         /public/images

# Build settings
markdown:           kramdown
permalink:          pretty

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
